### ISSUE TITLE
Työpajajärjestelmä 

### ISSUE THREAD

**Issue by Aromiii** [HuHu24/huhu-sovellus#136]
Vaeltaja voisi varata itselleen paikan työpajaan, jonne on rajoitettu osallistujamäärä 

eli aikatauluun tai johonkin muualle ominaisuus, että voi varata paikan ja tekijäpaneelista voisi katsoa ilmoittautuneiden listaa

**Comment by MitjaWasTaken** [comment]
Käyttäjä on vaeltaja ollessaan tekijä
