### ISSUE TITLE
Extra scrollbar

### ISSUE THREAD

**Issue by Aromiii** [HuHu24/huhu-sovellus#65]
![image](https://github.com/HuHu24/huhu-sovellus/assets/93449713/8576662d-4e36-4ca0-98cc-9478f01550b8)

Kaksi scrollbaria eli toinen vain pois ei mitään monimutkaista. Tapahtuu tiedotteet sivulla

**Comment by peedudu** [comment]
![kuva](https://github.com/HuHu24/huhu-sovellus/assets/66695333/30b40e10-ac39-46e0-bebb-edf5a6e48f08)
Ei näy mulla + mikä browser @Aromiii

**Comment by peedudu** [comment]
Couldnt recreate the issue, closing 🫡
