### ISSUE TITLE
Kaiken uin yhtenäistäminen 

### ISSUE THREAD

**Issue by Aromiii** [HuHu24/huhu-sovellus#83]
Vähän kaikkialla on eri fonttikokoja ja vahvuuksia, niin koko sovelluksen fonttien läpi käyminen ja kaiken muun visuaalinen ja niiden yhtenäistäminen. 

Myös olisi hyvä tehdä stadardi css tyylejä esim inputeille ja form napeille.

**Comment by peedudu** [comment]
Top "navbar" "otsikko" fontin vaihto poppins bold
